from BaseClasses import Location
from typing import TYPE_CHECKING

from worlds.deltarune.LogicHelper import (
    include_lose_recruits,
    include_mike_battle,
    include_mike_games,
    include_recruits,
)
from worlds.deltarune.Locations import LocationData, LocationGroups, LocationIDs
from worlds.deltarune.Regions import Regions

if TYPE_CHECKING:
    from .. import DeltaruneWorld

chapter4_locations = {
    Regions.ch4_castle_town: [
        LocationData(
            LocationIDs.ch4_castle_town_top_chef_gift,
            group=LocationGroups.chapter4,
        ),
        LocationData(LocationIDs.ch4_castle_town_mike_chest, group=LocationGroups.chapter4),
    ],
    Regions.ch4_dojo: [
        LocationData(
            LocationIDs.ch4_castle_town_lanino_elnina_challenge,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_mike_room: [
        LocationData(
            LocationIDs.ch4_castle_town_mike_defeat,
            should_be_included=include_mike_battle,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_battat_bronze,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_battat_silver,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_battat_gold,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_battat_platinum,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_jongler_bronze,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_jongler_silver,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_jongler_gold,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_jongler_platinum,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_pluey_bronze,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_pluey_silver,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_pluey_gold,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_mike_pluey_platinum,
            should_be_included=include_mike_games,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_dark_sanctuary: [
        LocationData(
            LocationIDs.ch4_dark_sanctuary_jockington_prophecy_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_chest_in_first_dark_area,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_worship_room_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_lantern_puzzle_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_library_chest_1,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_library_chest_2,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_jackenstein_gift,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_guei,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_balthizard,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_bibliox,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_mizzle,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_guei,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_balthizard,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_bibliox,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_mizzle,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_old_man_shop: [
        LocationData(LocationIDs.ch4_old_man_shop_1, group=LocationGroups.chapter4),
        LocationData(LocationIDs.ch4_old_man_shop_2, group=LocationGroups.chapter4),
        LocationData(LocationIDs.ch4_old_man_shop_3, group=LocationGroups.chapter4),
        LocationData(LocationIDs.ch4_old_man_shop_4, group=LocationGroups.chapter4),
    ],
    Regions.ch4_dark_sanctuary_claimbclaws: [
        LocationData(
            LocationIDs.ch4_dark_sanctuary_climbing_tutorial_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_cuptain_pillar_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_sleeping_mizzle_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_hidden_climbing_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_sheetmusic,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_miss_mizzle,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_miss_mizzle,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_gerson: [
        LocationData(
            LocationIDs.ch4_dark_sanctuary_hammer_of_justice_defeat_item_1,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_dark_sanctuary_hammer_of_justice_defeat_item_2,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_second_sanctuary: [
        LocationData(
            LocationIDs.ch4_dark_sanctuary_fountain_sealed,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_wall_climbing_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_waterfall_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_man,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_moss,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_destroyed_piano_block_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_winglade,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_organikk,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_winglade,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_organikk,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_second_sanctuary_post_wicabel: [
        LocationData(
            LocationIDs.ch4_second_sanctuary_gallery_prophecy_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_second_sanctuary_fountain_sealed,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_recruit_wicabel,
            should_be_included=include_recruits,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_lost_wicabel,
            should_be_included=include_lose_recruits,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_third_sanctuary: [
        LocationData(
            LocationIDs.ch4_third_sanctuary_annoying_dog,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_third_sanctuary_speed_climbing_chest,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_third_sanctuary_dark_area_chest,
            group=LocationGroups.chapter4,
        ),
    ],
    Regions.ch4_titan_fight: [
        LocationData(
            LocationIDs.ch4_third_sanctuary_titan_defeat,
            group=LocationGroups.chapter4,
        ),
        LocationData(
            LocationIDs.ch4_third_sanctuary_fountain_sealed,
            group=LocationGroups.chapter4,
        ),
    ],
}
